### PR TITLE
Turning on reference counting and fixing issue with performance test …

### PR DESCRIPTION
**Pull request by gsrunion**
…for array.

### CODE REVIEW

**Comment by gsrunion** [comment]
Pull requests don't behave as I expected and additional changes were included that I didn't intend. Closing pull request.

**Comment by gsrunion** [comment]
You can cherry pick d1161a9b96e0a49cc49669cff7046f3afe62ebe2. That is the only commit I was intending to merge.

**Comment by bcachet** [comment]
Thanks for your Pull Request.
To be honest I have worked on this project long time ago and I am not really involved in the development any more. I do not have sufficient expertise to judge your improvement => I will not integrate modifications to the project

I hope you have fun hacking on this project

**Comment by gsrunion** [comment]
Sure. I have played around with OO C concepts for a while and liked your
spin on it. Thanks for putting on github.

On Fri, Jun 17, 2016 at 3:15 PM, Bertrand Cachet <notifications@github.com>
wrote:

> Thanks for your Pull Request.
> To be honest I have worked on this project long time ago and I am not
> really involved in the development any more. I do not have sufficient
> expertise to judge your improvement => I will not integrate modifications
> to the project
>
> I hope you have fun hacking on this project
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/bcachet/booc/pull/1#issuecomment-226857267>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB3nzL95-OVExm72abFdJV8tVgH2-Lxoks5qMvJRgaJpZM4I36tA>
> .
>



-- 
Regards,
    Steve Runion

**Comment by bcachet** [comment]
I commit your correction (https://github.com/bcachet/booc/commit/d1161a9b96e0a49cc49669cff7046f3afe62ebe2)
And I will close your Pull Request

**Pull request closed without merging**
